---
- name: "1. Download the binary file on Jenkins Server"
  hosts: localhost
  vars:
    file_url: "{{ file_download_url }}"
    file_dest: "{{ file_download_dest }}"
  tasks:
    - name: Download the binary file
      block:
        - name: 1-1 Download the binary file
          get_url:
            url: "{{ file_url }}"
            dest: "{{ file_dest }}/{{ file_url.split('/')[-1] }}"
          register: download_result

        - name: Set download result as a global fact
          set_fact:
            downloaded_file: "{{ download_result.dest }}"
          no_log: true

        - name: Get file stats
          stat:
            path: "{{ downloaded_file }}"
          register: file_info
          no_log: true

        - name: Calculate MD5 checksum
          shell: "md5sum {{ downloaded_file }} | awk '{ print $1 }'"
          register: md5_result
          no_log: true

        - name: 1-2 Download completed
          debug:
            msg: "file={{ downloaded_file }}    size={{ (file_info.stat.size / 1024 / 1024) | round(2) }}MB     MD5={{ md5_result.stdout }}"

      rescue:
        - name: 1-2 ERROR found
          debug:
            msg: "Downloading file has an issue. Please check the config"
          
        - name: 1-3 EXIT playbook
          fail:
            msg: "Stopping the playbook because the file download failed"
