---
- name: [test] service en gwemix version rollback
  hosts: "{{ host }}"
  become: yes
  become_user: "{{ ansible_user }}" 

  vars:
    new_version_dir: "/data/wemix/new_version"
    bin_dir: "/data/wemix/bin"
    download_url: "https://github.com/wemixarchive/go-wemix/releases/download/w0.10.7/gwemix-v0.10.7-linux-rocksdb.tar.gz"

  tasks:
    - name: create directory
      file:
        path: "{{ new_version_dir }}"
        state: directory

    - name: tar.gz download
      get_url:
        url: "{{ download_url }}"
        dest: "{{ new_version_dir }}/gwemix.tar.gz"
