---
- name: service en gwemix version rollback
  hosts: "{{ host }}"
  become: yes
  become_user: "{{ ansible_user }}" 

  vars:
    new_version_dir: "/data/wemix/new_version"
    bin_dir: "/data/wemix/bin"
    download_url: "https://github.com/wemixarchive/go-wemix/releases/download/w0.10.7/gwemix-v0.10.7-linux-rocksdb.tar.gz"

  tasks:
    - name: create directory
      file:
        path: "{{ new_version_dir }}"
        state: directory

    - name: tar.gz download
      get_url:
        url: "{{ download_url }}"
        dest: "{{ new_version_dir }}/gwemix.tar.gz"

    - name: tar.gz extract
      unarchive:
        src: "{{ new_version_dir }}/gwemix.tar.gz"
        dest: "{{ new_version_dir }}/"
        remote_src: yes
        creates: "{{ new_version_dir }}/bin/"

    - name: backup old bin dir
      command: rsync -a {{ bin_dir }}/ {{ bin_dir }}_old_backup/
      changed_when: false

    - name: replace new bin dir
      command: rsync -a {{ new_version_dir }}/bin/ {{ bin_dir }}/
      changed_when: true

    - name: gwemix restart service
      command: "{{ bin_dir }}/gwemix.sh restart"
      async: 10
      poll: 2
